//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.296
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LPS.RfidOn.LPSSer {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/LPS.Services")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmpolyeeOR", Namespace="http://schemas.datacontract.org/2004/07/LPS.Model.Sys")]
    [System.SerializableAttribute()]
    public partial class EmpolyeeOR : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmpolyeeAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> EmpolyeeBirthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmpolyeeCardIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmpolyeeCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> EmpolyeeCreateDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> EmpolyeeDeletedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmpolyeeEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> EmpolyeeEntryDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmpolyeeHometownField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmpolyeeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmpolyeeIsDeletedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmpolyeeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmpolyeePhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmpolyeePyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmpolyeeRfidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmpolyeeSexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResultMsgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoseNameListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserPwdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmpolyeeAddress {
            get {
                return this.EmpolyeeAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpolyeeAddressField, value) != true)) {
                    this.EmpolyeeAddressField = value;
                    this.RaisePropertyChanged("EmpolyeeAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> EmpolyeeBirth {
            get {
                return this.EmpolyeeBirthField;
            }
            set {
                if ((this.EmpolyeeBirthField.Equals(value) != true)) {
                    this.EmpolyeeBirthField = value;
                    this.RaisePropertyChanged("EmpolyeeBirth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmpolyeeCardId {
            get {
                return this.EmpolyeeCardIdField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpolyeeCardIdField, value) != true)) {
                    this.EmpolyeeCardIdField = value;
                    this.RaisePropertyChanged("EmpolyeeCardId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmpolyeeCode {
            get {
                return this.EmpolyeeCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpolyeeCodeField, value) != true)) {
                    this.EmpolyeeCodeField = value;
                    this.RaisePropertyChanged("EmpolyeeCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> EmpolyeeCreateDate {
            get {
                return this.EmpolyeeCreateDateField;
            }
            set {
                if ((this.EmpolyeeCreateDateField.Equals(value) != true)) {
                    this.EmpolyeeCreateDateField = value;
                    this.RaisePropertyChanged("EmpolyeeCreateDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> EmpolyeeDeletedDate {
            get {
                return this.EmpolyeeDeletedDateField;
            }
            set {
                if ((this.EmpolyeeDeletedDateField.Equals(value) != true)) {
                    this.EmpolyeeDeletedDateField = value;
                    this.RaisePropertyChanged("EmpolyeeDeletedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmpolyeeEmail {
            get {
                return this.EmpolyeeEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpolyeeEmailField, value) != true)) {
                    this.EmpolyeeEmailField = value;
                    this.RaisePropertyChanged("EmpolyeeEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> EmpolyeeEntryDate {
            get {
                return this.EmpolyeeEntryDateField;
            }
            set {
                if ((this.EmpolyeeEntryDateField.Equals(value) != true)) {
                    this.EmpolyeeEntryDateField = value;
                    this.RaisePropertyChanged("EmpolyeeEntryDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmpolyeeHometown {
            get {
                return this.EmpolyeeHometownField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpolyeeHometownField, value) != true)) {
                    this.EmpolyeeHometownField = value;
                    this.RaisePropertyChanged("EmpolyeeHometown");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmpolyeeId {
            get {
                return this.EmpolyeeIdField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpolyeeIdField, value) != true)) {
                    this.EmpolyeeIdField = value;
                    this.RaisePropertyChanged("EmpolyeeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmpolyeeIsDeleted {
            get {
                return this.EmpolyeeIsDeletedField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpolyeeIsDeletedField, value) != true)) {
                    this.EmpolyeeIsDeletedField = value;
                    this.RaisePropertyChanged("EmpolyeeIsDeleted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmpolyeeName {
            get {
                return this.EmpolyeeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpolyeeNameField, value) != true)) {
                    this.EmpolyeeNameField = value;
                    this.RaisePropertyChanged("EmpolyeeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmpolyeePhone {
            get {
                return this.EmpolyeePhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpolyeePhoneField, value) != true)) {
                    this.EmpolyeePhoneField = value;
                    this.RaisePropertyChanged("EmpolyeePhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmpolyeePy {
            get {
                return this.EmpolyeePyField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpolyeePyField, value) != true)) {
                    this.EmpolyeePyField = value;
                    this.RaisePropertyChanged("EmpolyeePy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmpolyeeRfid {
            get {
                return this.EmpolyeeRfidField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpolyeeRfidField, value) != true)) {
                    this.EmpolyeeRfidField = value;
                    this.RaisePropertyChanged("EmpolyeeRfid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmpolyeeSex {
            get {
                return this.EmpolyeeSexField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpolyeeSexField, value) != true)) {
                    this.EmpolyeeSexField = value;
                    this.RaisePropertyChanged("EmpolyeeSex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResultMsg {
            get {
                return this.ResultMsgField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultMsgField, value) != true)) {
                    this.ResultMsgField = value;
                    this.RaisePropertyChanged("ResultMsg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoseNameList {
            get {
                return this.RoseNameListField;
            }
            set {
                if ((object.ReferenceEquals(this.RoseNameListField, value) != true)) {
                    this.RoseNameListField = value;
                    this.RaisePropertyChanged("RoseNameList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIdField, value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserPwd {
            get {
                return this.UserPwdField;
            }
            set {
                if ((object.ReferenceEquals(this.UserPwdField, value) != true)) {
                    this.UserPwdField = value;
                    this.RaisePropertyChanged("UserPwd");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FarmerRfidOR", Namespace="http://schemas.datacontract.org/2004/07/LPS.Model.Pur")]
    [System.SerializableAttribute()]
    public partial class FarmerRfidOR : LPS.RfidOn.LPSSer.EntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FarmerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RfidField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FarmerId {
            get {
                return this.FarmerIdField;
            }
            set {
                if ((object.ReferenceEquals(this.FarmerIdField, value) != true)) {
                    this.FarmerIdField = value;
                    this.RaisePropertyChanged("FarmerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Rfid {
            get {
                return this.RfidField;
            }
            set {
                if ((object.ReferenceEquals(this.RfidField, value) != true)) {
                    this.RfidField = value;
                    this.RaisePropertyChanged("Rfid");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityObject", Namespace="http://schemas.datacontract.org/2004/07/LPS.Model")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LPS.RfidOn.LPSSer.FarmerRfidOR))]
    public partial class EntityObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LPSSer.ILPSService")]
    public interface ILPSService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILPSService/GetData", ReplyAction="http://tempuri.org/ILPSService/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILPSService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/ILPSService/GetDataUsingDataContractResponse")]
        LPS.RfidOn.LPSSer.CompositeType GetDataUsingDataContract(LPS.RfidOn.LPSSer.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILPSService/Login", ReplyAction="http://tempuri.org/ILPSService/LoginResponse")]
        LPS.RfidOn.LPSSer.EmpolyeeOR Login(string UserCode, string userPWD);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILPSService/SaveFarmerRfid", ReplyAction="http://tempuri.org/ILPSService/SaveFarmerRfidResponse")]
        string SaveFarmerRfid(LPS.RfidOn.LPSSer.FarmerRfidOR[] ListOR);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILPSServiceChannel : LPS.RfidOn.LPSSer.ILPSService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LPSServiceClient : System.ServiceModel.ClientBase<LPS.RfidOn.LPSSer.ILPSService>, LPS.RfidOn.LPSSer.ILPSService {
        
        public LPSServiceClient() {
        }
        
        public LPSServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LPSServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LPSServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LPSServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public LPS.RfidOn.LPSSer.CompositeType GetDataUsingDataContract(LPS.RfidOn.LPSSer.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public LPS.RfidOn.LPSSer.EmpolyeeOR Login(string UserCode, string userPWD) {
            return base.Channel.Login(UserCode, userPWD);
        }
        
        public string SaveFarmerRfid(LPS.RfidOn.LPSSer.FarmerRfidOR[] ListOR) {
            return base.Channel.SaveFarmerRfid(ListOR);
        }
    }
}
